[package]
name = "supabar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "cmd"
path = "src/bin/cmd.rs"

[[bin]]
name = "paths"
path = "src/bin/paths.rs"

[dependencies]
anyhow = "1.0.57"
gio = "0.15.11"
notify = "4.0.17"
rustyline = "9.1.2"
rustyline-derive = "0.6.0"
standard_paths = "1.1.0"
thiserror = "1.0.31"
turbosql = "0.5.0"
whoami = "1.2.1"
