[package]
name = "supabar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "cmd"
path = "src/bin/cmd.rs"

[dependencies]
anyhow = "1.0.57"
rustyline = "9.1.2"
rustyline-derive = "0.6.0"
thiserror = "1.0.31"
turbosql = "0.5.0"
