[toolchain]
channel = "nightly"
components = [
    "cargo",
    "clippy",
    "rust-analysis",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt",
]
targets = [
    "x86_64-unknown-linux-gnu"
]
